# Script runs on Push targeted at the new branch
name: new branch CI

on:
  push:
    branches:
      - 'feature/*' # CI request triggers for all branches that start with feature/

# Uncomment the following line if you want to disable pull request triggers
# pr: none

jobs:
  build:
    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Restore
      run: dotnet restore ${{ github.workspace }}/SchoolManagement_API/SchoolManagement.API.csproj

    - name: Build
      run: dotnet build ${{ github.workspace }}/SchoolManagement_API/SchoolManagement.API.csproj --configuration Release

    - name: Test
      run: dotnet test ${{ github.workspace }}/Schoolmanagement.UnitTest/SchoolManagement.UnitTest.csproj --configuration Release

    - name: Publish
      run: dotnet publish ${{ github.workspace }}/SchoolManagement_API/SchoolManagement.API.csproj --configuration Release --output ${{ github.workspace }}/build_output
