# Script runs on PR targeted at the main branch
name: CI

on:
  push:
    branches:
      - 'feature/*' # CI request triggers for all branches that start with feature/

# Uncomment the following line if you want to disable pull request triggers
# pr: none

jobs:
  build:
    runs-on: ubuntu-latest

    variables:
      RestoreBuildProjects: '**/*.csproj'

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Restore
      run: dotnet restore ${{ github.workspace }}/'**/*.csproj'

    - name: Build
      run: dotnet build ${{ github.workspace }}/'**/*.csproj' --configuration Release

    - name: Test
      run: dotnet test ${{ github.workspace }}/'**/*[Tt]est/*.csproj' --configuration Release

    - name: Publish
      run: dotnet publish ${{ github.workspace }}/'**/*.csproj' --configuration Release --output ${{ github.workspace }}/build_output
